Backup

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -12,10 +12,10 @@ MYSQL_ROOT_PASSWORD="$1"
 mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > backup.sql
 
 # Check if the mysqldump command was successful
-if ! mysqldump -u user -p password database > backup.sql;then
-  echo "Error: Failed to generate MySQL dump"
-  exit 1
-fi
+# if ! mysqldump -u user -p password database > backup.sql;then
+# echo "Error: Failed to generate MySQL dump"
+# exit 1
+# fi
 
 # Get the current date in the format day-month-year
 DATE=$(date +%d-%m-%Y)
@@ -24,9 +24,9 @@ DATE=$(date +%d-%m-%Y)
 tar -czf "${DATE}.tar.gz" backup.sql
 
 # Check if the tar command was successful
-if ! cp backup.sql /backup/location/; then
-  echo "Error: Failed to create tar.gz archive"
-  exit 1
-fi
+# if ! cp backup.sql /backup/location/; then
+#  echo "Error: Failed to create tar.gz archive"
+#  exit 1
+# fi
 
 echo "Backup successfully created: ${DATE}.tar.gz"
